openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API documentation for Contacts App
tags:
  - name: Contacts
    description: Operations about contacts
  - name: Auth
    description: Operations about user authentication
servers:
  - url: https://nodejs-hw-mongodb-6-rc89.onrender.com
paths:
  /contacts:
    get:
      $ref: '../src/swagger/paths/contacts/get.yaml'
    post:
      $ref: '../src/swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../src/swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../src/swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../src/swagger/paths/contacts/{id}/delete.yaml'
  /register:
    post:
      $ref: '../src/swagger/paths/auth/register.yaml'
  /login:
    post:
      $ref: '../src/swagger/paths/auth/login.yaml'
  /logout:
    post:
      $ref: '../src/swagger/paths/auth/logout.yaml'
  /refresh:
    post:
      $ref: '../src/swagger/paths/auth/refresh.yaml'
  /send-reset-email:
    post:
      $ref: '../src/swagger/paths/auth/registerUserPassword.yaml'
  /reset-pwd:
    post:
      $ref: '../src/swagger/paths/auth/resetPassword.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
